-- ============================================================================
-- DZQL Compiled Functions for: acts_for
-- Generated: 2025-11-16T01:38:54.321Z
--
-- This file was automatically generated by the DZQL Compiler.
-- Do not edit directly - regenerate from entity definition.
-- ============================================================================



-- GET operation for acts_for
CREATE OR REPLACE FUNCTION get_acts_for(
  p_id INT,
  p_user_id INT,
  p_on_date TIMESTAMPTZ DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
  v_record acts_for%ROWTYPE;
BEGIN
  -- Fetch the record
  SELECT * INTO v_record
  FROM acts_for
  WHERE id = p_id
    AND valid_from <= COALESCE(p_on_date, NOW())
    AND (valid_to > COALESCE(p_on_date, NOW()) OR valid_to IS NULL);

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Record not found: % with id=%', 'acts_for', p_id;
  END IF;

  -- Convert to JSONB
  v_result := to_jsonb(v_record);

  -- Check view permission
  IF NOT can_view_acts_for(p_user_id, v_result) THEN
    RAISE EXCEPTION 'Permission denied: view on acts_for';
  END IF;


  -- Expand user (foreign key)
  IF v_record.user_id IS NOT NULL THEN
    v_result := v_result || jsonb_build_object(
      'user',
      (SELECT to_jsonb(t.*) FROM users t WHERE t.id = v_record.user_id)
    );
  END IF;
  -- Expand org (foreign key)
  IF v_record.org_id IS NOT NULL THEN
    v_result := v_result || jsonb_build_object(
      'org',
      (SELECT to_jsonb(t.*) FROM organisations t WHERE t.id = v_record.org_id)
    );
  END IF;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SAVE operation for acts_for
CREATE OR REPLACE FUNCTION save_acts_for(
  p_data JSONB,
  p_user_id INT
) RETURNS JSONB AS $$
DECLARE
  v_result acts_for%ROWTYPE;
  v_existing acts_for%ROWTYPE;
  v_is_insert BOOLEAN := false;
  v_notify_users INT[];
BEGIN
  -- Determine if this is insert or update
  IF p_data->>'id' IS NULL THEN
    v_is_insert := true;
  ELSE
    -- Try to fetch existing record
    SELECT * INTO v_existing
    FROM acts_for
    WHERE id = (p_data->>'id')::int;

    v_is_insert := NOT FOUND;
  END IF;

  -- Check permissions
  IF v_is_insert THEN
    IF NOT can_create_acts_for(p_user_id, p_data) THEN
      RAISE EXCEPTION 'Permission denied: create on acts_for';
    END IF;
  ELSE
    IF NOT can_update_acts_for(p_user_id, to_jsonb(v_existing)) THEN
      RAISE EXCEPTION 'Permission denied: update on acts_for';
    END IF;
  END IF;

  -- Perform UPSERT
  IF v_is_insert THEN
    INSERT INTO acts_for (
      SELECT string_agg(quote_ident(key), ', ') FROM jsonb_object_keys(p_data) key
    ) VALUES (
      SELECT string_agg(quote_literal(value), ', ') FROM jsonb_each_text(p_data) kv(key, value)
    ) RETURNING * INTO v_result;
  ELSE
    UPDATE acts_for
    SET SELECT string_agg(quote_ident(key) || ' = ' || quote_literal(value), ', ')
      FROM jsonb_each_text(p_data) kv(key, value)
      WHERE key != 'id'
    WHERE id = (p_data->>'id')::int
    RETURNING * INTO v_result;
  END IF;




  RETURN to_jsonb(v_result);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- DELETE operation for acts_for
CREATE OR REPLACE FUNCTION delete_acts_for(
  p_id INT,
  p_user_id INT
) RETURNS JSONB AS $$
DECLARE
  v_result acts_for%ROWTYPE;
BEGIN
  -- Fetch record first
  SELECT * INTO v_result
  FROM acts_for
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Record not found: % with id=%', 'acts_for', p_id;
  END IF;

  -- Check delete permission
  IF NOT can_delete_acts_for(p_user_id, to_jsonb(v_result)) THEN
    RAISE EXCEPTION 'Permission denied: delete on acts_for';
  END IF;



  -- Perform delete
  DELETE FROM acts_for WHERE id = p_id RETURNING * INTO v_result;



  RETURN to_jsonb(v_result);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- LOOKUP operation for acts_for
CREATE OR REPLACE FUNCTION lookup_acts_for(
  p_filter TEXT DEFAULT NULL,
  p_user_id INT DEFAULT NULL,
  p_limit INT DEFAULT 50
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
BEGIN
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'value', id,
      'label', org_id
    ) ORDER BY org_id
  ), '[]'::jsonb) INTO v_result
  FROM acts_for
  WHERE (p_filter IS NULL OR org_id ILIKE '%' || p_filter || '%')
    AND valid_from <= COALESCE(p_on_date, NOW())
    AND (valid_to > COALESCE(p_on_date, NOW()) OR valid_to IS NULL)
  LIMIT p_limit;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SEARCH operation for acts_for
CREATE OR REPLACE FUNCTION search_acts_for(
  p_filters JSONB DEFAULT '{}',
  p_search TEXT DEFAULT NULL,
  p_sort JSONB DEFAULT NULL,
  p_page INT DEFAULT 1,
  p_limit INT DEFAULT 25,
  p_user_id INT DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_data JSONB;
  v_total INT;
  v_offset INT;
  v_sort_field TEXT;
  v_sort_order TEXT;
BEGIN
  v_offset := (p_page - 1) * p_limit;

  -- Extract sort parameters
  v_sort_field := COALESCE(p_sort->>'field', 'org_id');
  v_sort_order := COALESCE(p_sort->>'order', 'asc');

  -- Get total count
  SELECT COUNT(*) INTO v_total
  FROM acts_for
  WHERE (p_search IS NULL OR (org_id ILIKE '%' || p_search || '%' OR user_id ILIKE '%' || p_search || '%'))
    AND valid_from <= COALESCE(p_on_date, NOW())
    AND (valid_to > COALESCE(p_on_date, NOW()) OR valid_to IS NULL);

  -- Get data
  EXECUTE format('
    SELECT COALESCE(jsonb_agg(to_jsonb(t.*) ORDER BY %I %s), ''[]''::jsonb)
    FROM acts_for t
    WHERE (CAST(%L AS TEXT) IS NULL OR (org_id ILIKE '%' || p_search || '%' OR user_id ILIKE '%' || p_search || '%'))
    LIMIT %L OFFSET %L
  ', v_sort_field, v_sort_order, p_search, p_limit, v_offset) INTO v_data;

  RETURN jsonb_build_object(
    'data', v_data,
    'total', v_total,
    'page', p_page,
    'limit', p_limit
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;