-- ============================================================================
-- DZQL Compiled Functions for: users
-- Generated: 2025-11-16T07:42:37.063Z
--
-- This file was automatically generated by the DZQL Compiler.
-- Do not edit directly - regenerate from entity definition.
-- ============================================================================

-- Permission check: create on users (public access)
CREATE OR REPLACE FUNCTION can_create_users(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN true;  -- Public access
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: -- Anyone can register (public)
    'update on users
CREATE OR REPLACE FUNCTION can_-- Anyone can register (public)
    'update_users(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    (p_record->>'id')::int = p_user_id
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: -- Only the user themselves
    'delete on users
CREATE OR REPLACE FUNCTION can_-- Only the user themselves
    'delete_users(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    (p_record->>'id')::int = p_user_id
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: -- Only the user themselves
    'view on users (public access)
CREATE OR REPLACE FUNCTION can_-- Only the user themselves
    'view_users(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN true;  -- Public access
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- GET operation for users
CREATE OR REPLACE FUNCTION get_users(
  p_id INT,
  p_user_id INT,
  p_on_date TIMESTAMPTZ DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
  v_record users%ROWTYPE;
BEGIN
  -- Fetch the record
  SELECT * INTO v_record
  FROM users
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Record not found: % with id=%', 'users', p_id;
  END IF;

  -- Convert to JSONB
  v_result := to_jsonb(v_record);

  -- Check view permission
  IF NOT can_view_users(p_user_id, v_result) THEN
    RAISE EXCEPTION 'Permission denied: view on users';
  END IF;



  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SAVE operation for users
CREATE OR REPLACE FUNCTION save_users(
  p_data JSONB,
  p_user_id INT
) RETURNS JSONB AS $$
DECLARE
  v_result users%ROWTYPE;
  v_existing users%ROWTYPE;
  v_is_insert BOOLEAN := false;
  v_notify_users INT[];
BEGIN
  -- Determine if this is insert or update
  IF p_data->>'id' IS NULL THEN
    v_is_insert := true;
  ELSE
    -- Try to fetch existing record
    SELECT * INTO v_existing
    FROM users
    WHERE id = (p_data->>'id')::int;

    v_is_insert := NOT FOUND;
  END IF;

  -- Check permissions
  IF v_is_insert THEN
    IF NOT can_create_users(p_user_id, p_data) THEN
      RAISE EXCEPTION 'Permission denied: create on users';
    END IF;
  ELSE
    IF NOT can_update_users(p_user_id, to_jsonb(v_existing)) THEN
      RAISE EXCEPTION 'Permission denied: update on users';
    END IF;
  END IF;

  -- Perform UPSERT
  IF v_is_insert THEN
    INSERT INTO users (
      SELECT string_agg(quote_ident(key), ', ') FROM jsonb_object_keys(p_data) key
    ) VALUES (
      SELECT string_agg(quote_literal(value), ', ') FROM jsonb_each_text(p_data) kv(key, value)
    ) RETURNING * INTO v_result;
  ELSE
    UPDATE users
    SET SELECT string_agg(quote_ident(key) || ' = ' || quote_literal(value), ', ')
      FROM jsonb_each_text(p_data) kv(key, value)
      WHERE key != 'id'
    WHERE id = (p_data->>'id')::int
    RETURNING * INTO v_result;
  END IF;




  RETURN to_jsonb(v_result);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- DELETE operation for users
CREATE OR REPLACE FUNCTION delete_users(
  p_id INT,
  p_user_id INT
) RETURNS JSONB AS $$
DECLARE
  v_result users%ROWTYPE;
BEGIN
  -- Fetch record first
  SELECT * INTO v_result
  FROM users
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Record not found: % with id=%', 'users', p_id;
  END IF;

  -- Check delete permission
  IF NOT can_delete_users(p_user_id, to_jsonb(v_result)) THEN
    RAISE EXCEPTION 'Permission denied: delete on users';
  END IF;



  -- Perform delete
  DELETE FROM users WHERE id = p_id RETURNING * INTO v_result;



  RETURN to_jsonb(v_result);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- LOOKUP operation for users
CREATE OR REPLACE FUNCTION lookup_users(
  p_filter TEXT DEFAULT NULL,
  p_user_id INT DEFAULT NULL,
  p_limit INT DEFAULT 50
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
BEGIN
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'value', id,
      'label', name
    ) ORDER BY name
  ), '[]'::jsonb) INTO v_result
  FROM users
  WHERE (p_filter IS NULL OR name ILIKE '%' || p_filter || '%')
  LIMIT p_limit;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SEARCH operation for users
CREATE OR REPLACE FUNCTION search_users(
  p_filters JSONB DEFAULT '{}',
  p_search TEXT DEFAULT NULL,
  p_sort JSONB DEFAULT NULL,
  p_page INT DEFAULT 1,
  p_limit INT DEFAULT 25,
  p_user_id INT DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_data JSONB;
  v_total INT;
  v_offset INT;
  v_sort_field TEXT;
  v_sort_order TEXT;
BEGIN
  v_offset := (p_page - 1) * p_limit;

  -- Extract sort parameters
  v_sort_field := COALESCE(p_sort->>'field', 'name');
  v_sort_order := COALESCE(p_sort->>'order', 'asc');

  -- Get total count
  SELECT COUNT(*) INTO v_total
  FROM users
  WHERE (p_search IS NULL OR (name ILIKE '%' || p_search || '%' OR email ILIKE '%' || p_search || '%'));

  -- Get data
  EXECUTE format('
    SELECT COALESCE(jsonb_agg(to_jsonb(t.*) ORDER BY %I %s), ''[]''::jsonb)
    FROM users t
    WHERE (CAST(%L AS TEXT) IS NULL OR (name ILIKE '%' || p_search || '%' OR email ILIKE '%' || p_search || '%'))
    LIMIT %L OFFSET %L
  ', v_sort_field, v_sort_order, p_search, p_limit, v_offset) INTO v_data;

  RETURN jsonb_build_object(
    'data', v_data,
    'total', v_total,
    'page', p_page,
    'limit', p_limit
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;