/**
 * DZQL Compiler
 * Main compiler class that orchestrates parsing and code generation
 */

import { EntityParser } from './parser/entity-parser.js';
import { generatePermissionFunctions } from './codegen/permission-codegen.js';
import { generateOperations } from './codegen/operation-codegen.js';
import crypto from 'crypto';

export class DZQLCompiler {
  constructor(options = {}) {
    this.options = {
      includeComments: true,
      includeChecksums: true,
      ...options
    };
    this.parser = new EntityParser();
  }

  /**
   * Compile an entity definition to SQL
   * @param {Object} entity - Entity configuration
   * @returns {Object} Compilation result
   */
  compile(entity) {
    const startTime = Date.now();

    // Normalize entity configuration
    const normalizedEntity = this.parser.parseFromObject(entity);

    // Generate SQL sections
    const sections = [];

    // Header
    if (this.options.includeComments) {
      sections.push(this._generateHeader(normalizedEntity));
    }

    // Permission functions
    const permissionSQL = generatePermissionFunctions(
      normalizedEntity.tableName,
      normalizedEntity.permissionPaths
    );
    sections.push(permissionSQL);

    // Operation functions
    const operationSQL = generateOperations(normalizedEntity);
    sections.push(operationSQL);

    // Notification path resolution (if needed)
    if (normalizedEntity.notificationPaths &&
        Object.keys(normalizedEntity.notificationPaths).length > 0) {
      sections.push(this._generateNotificationFunction(normalizedEntity));
    }

    // Combine all sections
    const sql = sections.join('\n\n');

    // Calculate checksum
    const checksum = this._calculateChecksum(sql);

    const result = {
      tableName: normalizedEntity.tableName,
      sql,
      checksum,
      compilationTime: Date.now() - startTime,
      generatedAt: new Date().toISOString()
    };

    return result;
  }

  /**
   * Compile multiple entities
   * @param {Array} entities - Array of entity configurations
   * @returns {Object} Compilation results
   */
  compileAll(entities) {
    const results = [];
    const errors = [];

    for (const entity of entities) {
      try {
        const result = this.compile(entity);
        results.push(result);
      } catch (error) {
        errors.push({
          entity: entity.tableName || 'unknown',
          error: error.message
        });
      }
    }

    return {
      results,
      errors,
      summary: {
        total: entities.length,
        successful: results.length,
        failed: errors.length
      }
    };
  }

  /**
   * Compile from SQL file
   * @param {string} sqlContent - SQL file content
   * @returns {Object} Compilation results
   */
  compileFromSQL(sqlContent) {
    const registerCalls = sqlContent.match(/dzql\.register_entity\s*\([\s\S]*?\);/gi);

    if (!registerCalls) {
      return {
        results: [],
        errors: [],
        summary: { total: 0, successful: 0, failed: 0 }
      };
    }

    const entities = [];
    for (const call of registerCalls) {
      try {
        const entity = this.parser.parseFromSQL(call);
        entities.push(entity);
      } catch (error) {
        console.warn('Failed to parse entity:', error.message);
      }
    }

    return this.compileAll(entities);
  }

  /**
   * Generate file header
   * @private
   */
  _generateHeader(entity) {
    return `-- ============================================================================
-- DZQL Compiled Functions for: ${entity.tableName}
-- Generated: ${new Date().toISOString()}
--
-- This file was automatically generated by the DZQL Compiler.
-- Do not edit directly - regenerate from entity definition.
-- ============================================================================`;
  }

  /**
   * Generate notification path resolution function
   * @private
   */
  _generateNotificationFunction(entity) {
    return `-- Notification path resolution for ${entity.tableName}
CREATE OR REPLACE FUNCTION resolve_notification_paths_${entity.tableName}(
  p_record JSONB
) RETURNS INT[] AS $$
DECLARE
  v_users INT[] := ARRAY[]::INT[];
BEGIN
  -- TODO: Compile notification paths
  -- For now, return empty array
  RETURN v_users;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;`;
  }

  /**
   * Calculate SHA-256 checksum of SQL
   * @private
   */
  _calculateChecksum(sql) {
    return crypto.createHash('sha256').update(sql).digest('hex');
  }

  /**
   * Format SQL with proper indentation (basic)
   * @private
   */
  _formatSQL(sql) {
    // Basic formatting - could be enhanced
    return sql.trim();
  }
}

/**
 * Compile a single entity
 * @param {Object} entity - Entity configuration
 * @param {Object} options - Compiler options
 * @returns {Object} Compilation result
 */
export function compile(entity, options = {}) {
  const compiler = new DZQLCompiler(options);
  return compiler.compile(entity);
}

/**
 * Compile multiple entities
 * @param {Array} entities - Array of entity configurations
 * @param {Object} options - Compiler options
 * @returns {Object} Compilation results
 */
export function compileAll(entities, options = {}) {
  const compiler = new DZQLCompiler(options);
  return compiler.compileAll(entities);
}

/**
 * Compile from SQL file content
 * @param {string} sqlContent - SQL file content
 * @param {Object} options - Compiler options
 * @returns {Object} Compilation results
 */
export function compileFromSQL(sqlContent, options = {}) {
  const compiler = new DZQLCompiler(options);
  return compiler.compileFromSQL(sqlContent);
}
