/**
 * Compiled mode CRUD tests
 * Tests the compiled db.api functions generated by the DZQL compiler
 * Migrated from packages/blog/tests/
 */

import { describe, test, expect, beforeAll } from 'bun:test';
import { DZQLCompiler } from '../../packages/dzql/src/compiler/index.js';
import { setupTests, createTestUser, testEmail, testName } from '../setup/test-helpers.js';

const { sql } = setupTests();

describe('Compiled Mode - db.api CRUD Operations', () => {
  let aliceUserId;
  let bobUserId;
  let db;

  beforeAll(async () => {
    // Create blog schema
    await sql`
      CREATE TABLE IF NOT EXISTS users (
        id serial PRIMARY KEY,
        name text NOT NULL,
        email text UNIQUE NOT NULL,
        password_hash text NOT NULL,
        created_at timestamptz DEFAULT now()
      )
    `;

    await sql`
      CREATE TABLE IF NOT EXISTS posts (
        id serial PRIMARY KEY,
        title text NOT NULL,
        content text NOT NULL,
        summary text,
        author_id int REFERENCES users(id),
        created_at timestamptz DEFAULT now(),
        deleted_at timestamptz
      )
    `;

    await sql`
      CREATE TABLE IF NOT EXISTS comments (
        id serial PRIMARY KEY,
        content text NOT NULL,
        post_id int REFERENCES posts(id),
        author_id int REFERENCES users(id),
        created_at timestamptz DEFAULT now()
      )
    `;

    await sql`
      CREATE TABLE IF NOT EXISTS tags (
        id serial PRIMARY KEY,
        name text UNIQUE NOT NULL,
        created_at timestamptz DEFAULT now()
      )
    `;

    // Compile entities
    const compiler = new DZQLCompiler();

    const entitiesSQL = `
      SELECT dzql.register_entity(
        'users',
        'name',
        array['name', 'email'],
        '{}',
        false,
        '{}',
        '{}',
        jsonb_build_object(
          'view', array[]::text[],
          'create', array[]::text[],
          'update', array['@id'],
          'delete', array['@id']
        )
      );

      SELECT dzql.register_entity(
        'posts',
        'title',
        array['title', 'content', 'summary'],
        '{"author": "users"}',
        true,
        '{}',
        '{}',
        jsonb_build_object(
          'view', array[]::text[],
          'create', array[]::text[],
          'update', array['@author_id'],
          'delete', array['@author_id']
        )
      );

      SELECT dzql.register_entity(
        'comments',
        'content',
        array['content'],
        '{"author": "users", "post": "posts"}',
        false,
        '{}',
        '{}',
        jsonb_build_object(
          'view', array[]::text[],
          'create', array[]::text[],
          'update', array['@author_id'],
          'delete', array['@author_id']
        )
      );

      SELECT dzql.register_entity(
        'tags',
        'name',
        array['name'],
        '{}',
        false
      );
    `;

    const compiled = compiler.compileFromSQL(entitiesSQL);

    // Execute compiled SQL
    for (const result of compiled.results) {
      await sql.unsafe(result.sql);
    }

    // Create test users
    const alice = await createTestUser(sql, 'alice@blog.com');
    const bob = await createTestUser(sql, 'bob@blog.com');
    aliceUserId = alice.user_id;
    bobUserId = bob.user_id;

    // Create db.api wrapper
    db = { api: {} };

    // Helper to create API functions
    const createApiFunction = (fnName) => {
      return async (userId, params = {}) => {
        const result = await sql`
          SELECT ${sql(fnName)}(${userId}, ${JSON.stringify(params)}::jsonb) as result
        `;
        return result[0].result;
      };
    };

    // Register compiled API functions
    const entities = ['users', 'posts', 'comments', 'tags'];
    const operations = ['get', 'save', 'delete', 'search', 'lookup'];

    for (const entity of entities) {
      for (const op of operations) {
        const fnName = `${op}_${entity}`;
        db.api[fnName] = createApiFunction(fnName);
      }
    }

    // Special auth functions
    db.api.register_user = async ({ email, password }) => {
      const result = await sql`SELECT register_user(${email}, ${password}) as result`;
      return result[0].result;
    };

    db.api.login_user = async ({ email, password }) => {
      const result = await sql`SELECT login_user(${email}, ${password}) as result`;
      return result[0].result;
    };
  });

  describe('Authentication via compiled db.api', () => {
    test('register_user creates new user without exposing password_hash', async () => {
      const uniqueEmail = testEmail('compiled');
      const profile = await db.api.register_user({
        email: uniqueEmail,
        password: 'testpass123'
      });

      expect(profile).toHaveProperty('user_id');
      expect(profile).toHaveProperty('email', uniqueEmail);
      expect(profile).not.toHaveProperty('password_hash');
    });

    test('login_user authenticates with correct password', async () => {
      const profile = await db.api.login_user({
        email: 'alice@blog.com',
        password: 'testpass123'
      });

      expect(profile).toHaveProperty('user_id', aliceUserId);
      expect(profile).toHaveProperty('email', 'alice@blog.com');
      expect(profile).not.toHaveProperty('password_hash');
    });

    test('login_user rejects incorrect password', async () => {
      await expect(async () => {
        await db.api.login_user({ email: 'alice@blog.com', password: 'wrongpassword' });
      }).toThrow();
    });
  });

  describe('Posts CRUD via compiled db.api', () => {
    let postId;

    test('save_posts creates new post', async () => {
      const postData = {
        title: testName('Post'),
        content: 'This is the content of my post.',
        summary: 'Post summary',
        author_id: aliceUserId
      };
      const post = await db.api.save_posts(aliceUserId, { data: postData });

      expect(post).toHaveProperty('id');
      expect(post).toHaveProperty('title', postData.title);
      expect(post).toHaveProperty('author_id', aliceUserId);
      expect(post.deleted_at).toBeNull();

      postId = post.id;
    });

    test('get_posts returns post', async () => {
      const post = await db.api.get_posts(aliceUserId, { id: postId });

      expect(post).toHaveProperty('id', postId);
      expect(post).toHaveProperty('title');
    });

    test('search_posts finds posts', async () => {
      const response = await db.api.search_posts(aliceUserId, {});

      expect(response.data).toBeArray();
      expect(response.data.length).toBeGreaterThan(0);
      expect(response.total).toBeGreaterThan(0);
    });

    test('delete_posts soft deletes post', async () => {
      const post = await db.api.delete_posts(aliceUserId, { id: postId });

      expect(post.deleted_at).not.toBeNull();
    });
  });

  describe('Comments CRUD via compiled db.api', () => {
    let postId;
    let commentId;

    beforeAll(async () => {
      // Create a post for commenting
      const postData = {
        title: testName('CommentPost'),
        content: 'Content',
        author_id: aliceUserId
      };
      const post = await db.api.save_posts(aliceUserId, { data: postData });
      postId = post.id;
    });

    test('save_comments creates new comment', async () => {
      const commentData = {
        content: 'Great post!',
        post_id: postId,
        author_id: bobUserId
      };
      const comment = await db.api.save_comments(bobUserId, { data: commentData });

      expect(comment).toHaveProperty('id');
      expect(comment).toHaveProperty('content', 'Great post!');
      expect(comment).toHaveProperty('post_id', postId);
      expect(comment).toHaveProperty('author_id', bobUserId);

      commentId = comment.id;
    });

    test('get_comments returns comment', async () => {
      const comment = await db.api.get_comments(bobUserId, { id: commentId });

      expect(comment).toHaveProperty('id', commentId);
      expect(comment).toHaveProperty('content', 'Great post!');
    });

    test('search_comments finds comments with filter', async () => {
      const response = await db.api.search_comments(aliceUserId, {
        filters: { post_id: postId }
      });

      expect(response.data).toBeArray();
      expect(response.data.length).toBeGreaterThan(0);
      expect(response.data[0]).toHaveProperty('post_id', postId);
    });
  });

  describe('Users CRUD via compiled db.api', () => {
    test('get_users returns user without password_hash', async () => {
      const user = await db.api.get_users(aliceUserId, { id: aliceUserId });

      expect(user).toHaveProperty('id', aliceUserId);
      expect(user).toHaveProperty('email', 'alice@blog.com');
      expect(user).not.toHaveProperty('password_hash');
    });

    test('search_users returns users without password_hash', async () => {
      const response = await db.api.search_users(aliceUserId, {});

      expect(response.data).toBeArray();
      expect(response.data.length).toBeGreaterThan(0);
      expect(response.total).toBeGreaterThan(0);

      // Verify no user has password_hash
      response.data.forEach(user => {
        expect(user).not.toHaveProperty('password_hash');
        expect(user).toHaveProperty('id');
        expect(user).toHaveProperty('email');
      });
    });

    test('save_users creates new user', async () => {
      const uniqueEmail = testEmail('new-user');
      const userData = { name: testName('User'), email: uniqueEmail, password_hash: 'dummy' };
      const user = await db.api.save_users(aliceUserId, { data: userData });

      expect(user).toHaveProperty('id');
      expect(user).toHaveProperty('email', uniqueEmail);
      expect(user).not.toHaveProperty('password_hash');
    });

    test('lookup_users returns value/label pairs', async () => {
      const results = await db.api.lookup_users(aliceUserId, { filter: 'alice' });

      expect(results).toBeArray();
      expect(results.length).toBeGreaterThan(0);
      expect(results[0]).toHaveProperty('value');
      expect(results[0]).toHaveProperty('label');
    });
  });
});
