-- ============================================================================
-- DZQL Compiled Functions for: organisations
-- Generated: 2025-11-16T09:39:52.640Z
--
-- This file was automatically generated by the DZQL Compiler.
-- Do not edit directly - regenerate from entity definition.
-- ============================================================================

-- Permission check: view on organisations
CREATE OR REPLACE FUNCTION can_view_organisations(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    (p_record->>'owner_id')::int = p_user_id
      OR EXISTS (
        SELECT 1 FROM acts_for
        WHERE acts_for.org_id = (p_record->>'org_id')::int
          AND acts_for.valid_to IS NULL
          AND acts_for.user_id = p_user_id
      )
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: create on organisations
CREATE OR REPLACE FUNCTION can_create_organisations(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    false
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: update on organisations
CREATE OR REPLACE FUNCTION can_update_organisations(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    EXISTS (
        SELECT 1 FROM acts_for
        WHERE acts_for.org_id = (p_record->>'org_id')::int
          AND acts_for.valid_to IS NULL
          AND acts_for.user_id = p_user_id
      )
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: delete on organisations
CREATE OR REPLACE FUNCTION can_delete_organisations(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    (p_record->>'owner_id')::int = p_user_id
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- GET operation for organisations
CREATE OR REPLACE FUNCTION get_organisations(
  p_user_id INT,
  p_id INT,
  p_on_date TIMESTAMPTZ DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
  v_record organisations%ROWTYPE;
BEGIN
  -- Fetch the record
  SELECT * INTO v_record
  FROM organisations
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Record not found: % with id=%', 'organisations', p_id;
  END IF;

  -- Convert to JSONB
  v_result := to_jsonb(v_record);

  -- Check view permission
  IF NOT can_view_organisations(p_user_id, v_result) THEN
    RAISE EXCEPTION 'Permission denied: view on organisations';
  END IF;


  -- Expand org (foreign key)
  IF v_record.org_id IS NOT NULL THEN
    v_result := v_result || jsonb_build_object(
      'org',
      (SELECT to_jsonb(t.*) FROM acts_for t WHERE t.id = v_record.org_id)
    );
  END IF;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SAVE operation for organisations
CREATE OR REPLACE FUNCTION save_organisations(
  p_user_id INT,
  p_data JSONB
) RETURNS JSONB AS $$
DECLARE
  v_result organisations%ROWTYPE;
  v_existing organisations%ROWTYPE;
  v_is_insert BOOLEAN := false;
  v_notify_users INT[];
BEGIN
  -- Determine if this is insert or update
  IF p_data->>'id' IS NULL THEN
    v_is_insert := true;
  ELSE
    -- Try to fetch existing record
    SELECT * INTO v_existing
    FROM organisations
    WHERE id = (p_data->>'id')::int;

    v_is_insert := NOT FOUND;
  END IF;

  -- Check permissions
  IF v_is_insert THEN
    IF NOT can_create_organisations(p_user_id, p_data) THEN
      RAISE EXCEPTION 'Permission denied: create on organisations';
    END IF;
  ELSE
    IF NOT can_update_organisations(p_user_id, to_jsonb(v_existing)) THEN
      RAISE EXCEPTION 'Permission denied: update on organisations';
    END IF;
  END IF;

  -- Perform UPSERT
  IF v_is_insert THEN
    INSERT INTO organisations (
      SELECT string_agg(quote_ident(key), ', ') FROM jsonb_object_keys(p_data) key
    ) VALUES (
      SELECT string_agg(quote_literal(value), ', ') FROM jsonb_each_text(p_data) kv(key, value)
    ) RETURNING * INTO v_result;
  ELSE
    UPDATE organisations
    SET SELECT string_agg(quote_ident(key) || ' = ' || quote_literal(value), ', ')
      FROM jsonb_each_text(p_data) kv(key, value)
      WHERE key != 'id'
    WHERE id = (p_data->>'id')::int
    RETURNING * INTO v_result;
  END IF;


  -- Execute graph rules: on_create (if insert)
  IF v_is_insert THEN
    PERFORM _graph_organisations_on_create(p_user_id, to_jsonb(v_result));
  END IF;


  RETURN to_jsonb(v_result);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- DELETE operation for organisations
CREATE OR REPLACE FUNCTION delete_organisations(
  p_user_id INT,
  p_id INT
) RETURNS JSONB AS $$
DECLARE
  v_result organisations%ROWTYPE;
BEGIN
  -- Fetch record first
  SELECT * INTO v_result
  FROM organisations
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Record not found: % with id=%', 'organisations', p_id;
  END IF;

  -- Check delete permission
  IF NOT can_delete_organisations(p_user_id, to_jsonb(v_result)) THEN
    RAISE EXCEPTION 'Permission denied: delete on organisations';
  END IF;



  -- Perform delete
  DELETE FROM organisations WHERE id = p_id RETURNING * INTO v_result;



  RETURN to_jsonb(v_result);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- LOOKUP operation for organisations
CREATE OR REPLACE FUNCTION lookup_organisations(
  p_user_id INT,
  p_filter TEXT DEFAULT NULL,
  p_limit INT DEFAULT 50
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
BEGIN
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'value', id,
      'label', name
    ) ORDER BY name
  ), '[]'::jsonb) INTO v_result
  FROM organisations
  WHERE (p_filter IS NULL OR name ILIKE '%' || p_filter || '%')
  LIMIT p_limit;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SEARCH operation for organisations
CREATE OR REPLACE FUNCTION search_organisations(
  p_user_id INT,
  p_filters JSONB DEFAULT '{}',
  p_search TEXT DEFAULT NULL,
  p_sort JSONB DEFAULT NULL,
  p_page INT DEFAULT 1,
  p_limit INT DEFAULT 25
) RETURNS JSONB AS $$
DECLARE
  v_data JSONB;
  v_total INT;
  v_offset INT;
  v_sort_field TEXT;
  v_sort_order TEXT;
  v_where_clause TEXT := 'TRUE';
  v_field TEXT;
  v_filter JSONB;
  v_operator TEXT;
  v_value JSONB;
BEGIN
  v_offset := (p_page - 1) * p_limit;

  -- Extract sort parameters
  v_sort_field := COALESCE(p_sort->>'field', 'name');
  v_sort_order := COALESCE(p_sort->>'order', 'asc');

  -- Build WHERE clause from filters
  FOR v_field, v_filter IN SELECT * FROM jsonb_each(p_filters)
  LOOP
    -- Handle simple value (exact match)
    IF jsonb_typeof(v_filter) IN ('string', 'number', 'boolean') THEN
      v_where_clause := v_where_clause || format(' AND %I = %L', v_field, v_filter #>> '{}');
    ELSE
      -- Handle operator-based filters
      FOR v_operator, v_value IN SELECT * FROM jsonb_each(v_filter)
      LOOP
        CASE v_operator
          WHEN 'eq' THEN
            v_where_clause := v_where_clause || format(' AND %I = %L', v_field, v_value #>> '{}');
          WHEN 'ne' THEN
            v_where_clause := v_where_clause || format(' AND %I != %L', v_field, v_value #>> '{}');
          WHEN 'gt' THEN
            v_where_clause := v_where_clause || format(' AND %I > %L', v_field, v_value #>> '{}');
          WHEN 'gte' THEN
            v_where_clause := v_where_clause || format(' AND %I >= %L', v_field, v_value #>> '{}');
          WHEN 'lt' THEN
            v_where_clause := v_where_clause || format(' AND %I < %L', v_field, v_value #>> '{}');
          WHEN 'lte' THEN
            v_where_clause := v_where_clause || format(' AND %I <= %L', v_field, v_value #>> '{}');
          WHEN 'in' THEN
            v_where_clause := v_where_clause || format(' AND %I = ANY(%L::TEXT[])', v_field,
              (SELECT array_agg(value #>> '{}') FROM jsonb_array_elements(v_value) AS value));
          WHEN 'ilike' THEN
            v_where_clause := v_where_clause || format(' AND %I ILIKE %L', v_field, v_value #>> '{}');
          WHEN 'like' THEN
            v_where_clause := v_where_clause || format(' AND %I LIKE %L', v_field, v_value #>> '{}');
          ELSE
            -- Unknown operator, skip
        END CASE;
      END LOOP;
    END IF;
  END LOOP;

  -- Add search condition
  IF p_search IS NOT NULL THEN
    v_where_clause := v_where_clause || ' AND (name ILIKE '%' || p_search || '%' OR description ILIKE '%' || p_search || '%')';
  END IF;

  -- Add temporal filter
  v_where_clause := v_where_clause || '';

  -- Get total count
  EXECUTE format('SELECT COUNT(*) FROM organisations WHERE %s', v_where_clause) INTO v_total;

  -- Get data
  EXECUTE format('
    SELECT COALESCE(jsonb_agg(to_jsonb(t.*) ORDER BY %I %s), ''[]''::jsonb)
    FROM organisations t
    WHERE %s
    LIMIT %L OFFSET %L
  ', v_sort_field, v_sort_order, v_where_clause, p_limit, v_offset) INTO v_data;

  RETURN jsonb_build_object(
    'data', v_data,
    'total', v_total,
    'page', p_page,
    'limit', p_limit
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Graph rules: on_create on organisations
CREATE OR REPLACE FUNCTION _graph_organisations_on_create(
  p_user_id INT,
  p_record JSONB
) RETURNS VOID AS $$
BEGIN
  -- Creator becomes owner
  INSERT INTO acts_for (user_id, org_id, valid_from)
  VALUES (p_user_id, (p_record->>'id'), CURRENT_DATE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;