-- ============================================================================
-- DZQL Compiled Functions for: posts
-- Generated: 2025-11-16T17:16:39.633Z
--
-- This file was automatically generated by the DZQL Compiler.
-- Do not edit directly - regenerate from entity definition.
-- ============================================================================

-- Permission check: view on posts (public access)
CREATE OR REPLACE FUNCTION can_view_posts(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN true;  -- Public access
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: create on posts (public access)
CREATE OR REPLACE FUNCTION can_create_posts(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN true;  -- Public access
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: update on posts
CREATE OR REPLACE FUNCTION can_update_posts(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    (p_record->>'author_id')::int = p_user_id
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: delete on posts (public access)
CREATE OR REPLACE FUNCTION can_delete_posts(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN true;  -- Public access
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- GET operation for posts
CREATE OR REPLACE FUNCTION get_posts(
  p_user_id INT,
  p_id INT,
  p_on_date TIMESTAMPTZ DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
  v_record posts%ROWTYPE;
BEGIN
  -- Fetch the record
  SELECT * INTO v_record
  FROM posts
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Record not found: % with id=%', 'posts', p_id;
  END IF;

  -- Convert to JSONB
  v_result := to_jsonb(v_record);

  -- Check view permission
  IF NOT can_view_posts(p_user_id, v_result) THEN
    RAISE EXCEPTION 'Permission denied: view on posts';
  END IF;


  -- Expand author (foreign key)
  IF v_record.author_id IS NOT NULL THEN
    v_result := v_result || jsonb_build_object(
      'author',
      (SELECT to_jsonb(t.*) FROM users t WHERE t.id = v_record.author_id)
    );
  END IF;

  -- Remove sensitive fields (password_hash, etc.) from result
  v_result := v_result - 'password_hash' - 'password' - 'secret' - 'token';

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SAVE operation for posts
CREATE OR REPLACE FUNCTION save_posts(
  p_user_id INT,
  p_data JSONB
) RETURNS JSONB AS $$
DECLARE
  v_result posts%ROWTYPE;
  v_existing posts%ROWTYPE;
  v_output JSONB;
  v_is_insert BOOLEAN := false;
  v_notify_users INT[];
BEGIN
  -- Determine if this is insert or update
  IF p_data->>'id' IS NULL THEN
    v_is_insert := true;
  ELSE
    -- Try to fetch existing record
    SELECT * INTO v_existing
    FROM posts
    WHERE id = (p_data->>'id')::int;

    v_is_insert := NOT FOUND;
  END IF;

  -- Check permissions
  IF v_is_insert THEN
    IF NOT can_create_posts(p_user_id, p_data) THEN
      RAISE EXCEPTION 'Permission denied: create on posts';
    END IF;
  ELSE
    IF NOT can_update_posts(p_user_id, to_jsonb(v_existing)) THEN
      RAISE EXCEPTION 'Permission denied: update on posts';
    END IF;
  END IF;

  -- Perform UPSERT
  IF v_is_insert THEN
    -- Dynamic INSERT from JSONB
    EXECUTE (
      SELECT format(
        'INSERT INTO posts (%s) VALUES (%s) RETURNING *',
        string_agg(quote_ident(key), ', '),
        string_agg(quote_nullable(value), ', ')
      )
      FROM jsonb_each_text(p_data) kv(key, value)
    ) INTO v_result;
  ELSE
    -- Dynamic UPDATE from JSONB
    EXECUTE (
      SELECT format(
        'UPDATE posts SET %s WHERE id = %L RETURNING *',
        string_agg(quote_ident(key) || ' = ' || quote_nullable(value), ', '),
        (p_data->>'id')::int
      )
      FROM jsonb_each_text(p_data) kv(key, value)
      WHERE key != 'id'
    ) INTO v_result;
  END IF;



  -- Resolve notification recipients
  v_notify_users := ARRAY[]::INT[];

  -- Create event for real-time notifications
  INSERT INTO dzql.events (
    table_name,
    op,
    pk,
    before,
    after,
    user_id,
    notify_users
  ) VALUES (
    'posts',
    CASE WHEN v_is_insert THEN 'insert' ELSE 'update' END,
    jsonb_build_object('id', v_result.id),
    CASE WHEN NOT v_is_insert THEN to_jsonb(v_existing) ELSE NULL END,
    to_jsonb(v_result),
    p_user_id,
    v_notify_users
  );

  -- Prepare output (removing sensitive fields)
  v_output := to_jsonb(v_result);

  -- Remove sensitive fields (password_hash, etc.) from result
  v_output := v_output - 'password_hash' - 'password' - 'secret' - 'token';

  RETURN v_output;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- DELETE operation for posts
CREATE OR REPLACE FUNCTION delete_posts(
  p_user_id INT,
  p_id INT
) RETURNS JSONB AS $$
DECLARE
  v_result posts%ROWTYPE;
  v_output JSONB;
  v_notify_users INT[];
BEGIN
  -- Fetch record first
  SELECT * INTO v_result
  FROM posts
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Record not found: % with id=%', 'posts', p_id;
  END IF;

  -- Check delete permission
  IF NOT can_delete_posts(p_user_id, to_jsonb(v_result)) THEN
    RAISE EXCEPTION 'Permission denied: delete on posts';
  END IF;



  -- Perform delete
  UPDATE posts SET deleted_at = NOW() WHERE id = p_id RETURNING * INTO v_result;


  -- Resolve notification recipients
  v_notify_users := ARRAY[]::INT[];

  -- Create event for real-time notifications
  INSERT INTO dzql.events (
    table_name,
    op,
    pk,
    before,
    after,
    user_id,
    notify_users
  ) VALUES (
    'posts',
    'delete',
    jsonb_build_object('id', v_result.id),
    to_jsonb(v_result),
    NULL,
    p_user_id,
    v_notify_users
  );

  -- Prepare output (removing sensitive fields)
  v_output := to_jsonb(v_result);

  -- Remove sensitive fields (password_hash, etc.) from result
  v_output := v_output - 'password_hash' - 'password' - 'secret' - 'token';

  RETURN v_output;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- LOOKUP operation for posts
CREATE OR REPLACE FUNCTION lookup_posts(
  p_user_id INT,
  p_filter TEXT DEFAULT NULL,
  p_limit INT DEFAULT 50
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
BEGIN
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'value', id,
      'label', title
    ) ORDER BY title
  ), '[]'::jsonb) INTO v_result
  FROM posts
  WHERE (p_filter IS NULL OR title ILIKE '%' || p_filter || '%')
  LIMIT p_limit;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SEARCH operation for posts
CREATE OR REPLACE FUNCTION search_posts(
  p_user_id INT,
  p_filters JSONB DEFAULT '{}',
  p_search TEXT DEFAULT NULL,
  p_sort JSONB DEFAULT NULL,
  p_page INT DEFAULT 1,
  p_limit INT DEFAULT 25
) RETURNS JSONB AS $$
DECLARE
  v_data JSONB;
  v_total INT;
  v_offset INT;
  v_sort_field TEXT;
  v_sort_order TEXT;
  v_where_clause TEXT := 'TRUE';
  v_field TEXT;
  v_filter JSONB;
  v_operator TEXT;
  v_value JSONB;
BEGIN
  v_offset := (p_page - 1) * p_limit;

  -- Extract sort parameters
  v_sort_field := COALESCE(p_sort->>'field', 'title');
  v_sort_order := COALESCE(p_sort->>'order', 'asc');

  -- Build WHERE clause from filters
  FOR v_field, v_filter IN SELECT * FROM jsonb_each(p_filters)
  LOOP
    -- Handle simple value (exact match)
    IF jsonb_typeof(v_filter) IN ('string', 'number', 'boolean') THEN
      v_where_clause := v_where_clause || format(' AND %I = %L', v_field, v_filter #>> '{}');
    ELSE
      -- Handle operator-based filters
      FOR v_operator, v_value IN SELECT * FROM jsonb_each(v_filter)
      LOOP
        CASE v_operator
          WHEN 'eq' THEN
            v_where_clause := v_where_clause || format(' AND %I = %L', v_field, v_value #>> '{}');
          WHEN 'ne' THEN
            v_where_clause := v_where_clause || format(' AND %I != %L', v_field, v_value #>> '{}');
          WHEN 'gt' THEN
            v_where_clause := v_where_clause || format(' AND %I > %L', v_field, v_value #>> '{}');
          WHEN 'gte' THEN
            v_where_clause := v_where_clause || format(' AND %I >= %L', v_field, v_value #>> '{}');
          WHEN 'lt' THEN
            v_where_clause := v_where_clause || format(' AND %I < %L', v_field, v_value #>> '{}');
          WHEN 'lte' THEN
            v_where_clause := v_where_clause || format(' AND %I <= %L', v_field, v_value #>> '{}');
          WHEN 'in' THEN
            v_where_clause := v_where_clause || format(' AND %I = ANY(%L::TEXT[])', v_field,
              (SELECT array_agg(value #>> '{}') FROM jsonb_array_elements(v_value) AS value));
          WHEN 'ilike' THEN
            v_where_clause := v_where_clause || format(' AND %I ILIKE %L', v_field, v_value #>> '{}');
          WHEN 'like' THEN
            v_where_clause := v_where_clause || format(' AND %I LIKE %L', v_field, v_value #>> '{}');
          ELSE
            -- Unknown operator, skip
        END CASE;
      END LOOP;
    END IF;
  END LOOP;

  -- Add search condition
  IF p_search IS NOT NULL THEN
    v_where_clause := v_where_clause || ' AND (title ILIKE '%' || p_search || '%' OR content ILIKE '%' || p_search || '%' OR summary ILIKE '%' || p_search || '%')';
  END IF;

  -- Add temporal filter
  v_where_clause := v_where_clause || '';

  -- Get total count
  EXECUTE format('SELECT COUNT(*) FROM posts WHERE %s', v_where_clause) INTO v_total;

  -- Get data
  EXECUTE format('
    SELECT COALESCE(jsonb_agg(to_jsonb(t.*) ORDER BY %I %s), ''[]''::jsonb)
    FROM posts t
    WHERE %s
    LIMIT %L OFFSET %L
  ', v_sort_field, v_sort_order, v_where_clause, p_limit, v_offset) INTO v_data;


  -- Remove sensitive fields from each record in the array
  v_data := (
    SELECT jsonb_agg(elem - 'password_hash' - 'password' - 'secret' - 'token')
    FROM jsonb_array_elements(v_data) elem
  );

  RETURN jsonb_build_object(
    'data', v_data,
    'total', v_total,
    'page', p_page,
    'limit', p_limit
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;