services:
  postgres:
    image: postgres:latest
    container_name: dzql-blog-postgres
    environment:
      POSTGRES_DB: dzql_blog
      POSTGRES_USER: dzql
      POSTGRES_PASSWORD: dzql
    ports:
      - "5432:5432"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d:ro
