import { Manifest, FunctionDef } from "./manifest.js";
import { generateTypeDefinitions } from "./types.js";

function toPascalCase(str: string): string {
  return str.replace(/(^|_)([a-z])/g, (g) => g[g.length - 1]!.toUpperCase());
}

/**
 * Generate a TypeScript client SDK
 */
export function generateClientSDK(manifest: Manifest): string {
  // Separate regular functions from subscriptions
  const regularFunctions = Object.entries(manifest.functions)
    .filter(([_, def]) => !def.isSubscription);
  const subscriptionFunctions = Object.entries(manifest.functions)
    .filter(([_, def]) => def.isSubscription);

  // Generate entity types
  const typeDefs = generateTypeDefinitions(manifest.entities, manifest.subscribables);

  // Generate API interface with proper types
  const apiMethods = Object.entries(manifest.functions).map(([funcName, def]) => {
    const isSubscription = def.isSubscription;
    const parts = funcName.split('_');
    const op = parts[0];
    const entity = parts.slice(1).join('_');
    const pascalEntity = toPascalCase(entity);

    // Check if this entity exists in manifest
    const entityExists = manifest.entities[entity];

    let paramType = 'Record<string, unknown>';
    let returnType = 'unknown';

    if (isSubscription) {
      // subscribe_venue_detail -> VenueDetailParams
      paramType = `${pascalEntity}Params`;
      returnType = 'void';
      return `  ${funcName}: (params: ${paramType}, callback: (data: unknown) => void) => Promise<() => ${returnType}>;`;
    } else if (op === 'get' && entityExists) {
      // get_venue_detail (subscribable getter) vs get_venues (entity getter)
      if (manifest.subscribables?.[entity]) {
        paramType = `${pascalEntity}Params`;
        returnType = 'unknown';
      } else {
        paramType = `${pascalEntity}PK`;
        returnType = `${pascalEntity} | null`;
      }
    } else if (op === 'save' && entityExists) {
      paramType = `Save${pascalEntity}Params`;
      returnType = pascalEntity;
    } else if (op === 'delete' && entityExists) {
      paramType = `${pascalEntity}PK`;
      returnType = pascalEntity;
    } else if (op === 'search' && entityExists) {
      paramType = `Search${pascalEntity}Params`;
      returnType = `${pascalEntity}[]`;
    } else if (op === 'lookup' && entityExists) {
      paramType = `Lookup${pascalEntity}Params`;
      returnType = `${pascalEntity}[]`;
    }
    // Custom functions and auth functions stay as Record<string, unknown>

    return `  ${funcName}: (params: ${paramType}) => Promise<${returnType}>;`;
  }).join('\n');

  return `// Generated by TZQL Compiler v${manifest.version}
// Do not edit this file directly.

import { WebSocketManager } from 'tzql/client';

${typeDefs}

/** API interface with typed methods */
export interface TzqlAPI {
${apiMethods}
}

/** Extended WebSocket manager with typed API */
export class GeneratedWebSocketManager extends WebSocketManager {
  api: TzqlAPI;

  constructor(options: { url?: string; reconnect?: boolean } = {}) {
    super(options);
    this.api = {
${regularFunctions.map(([funcName]) =>
      `      ${funcName}: (params: Record<string, unknown>) => this.call('${funcName}', params),`
).join('\n')}
${subscriptionFunctions.map(([funcName]) =>
      `      ${funcName}: (params: Record<string, unknown>, callback: (data: unknown) => void) => this.subscribe('${funcName}', params, callback),`
).join('\n')}
    } as TzqlAPI;
  }
}

/** Singleton WebSocket instance */
export const ws = new GeneratedWebSocketManager();
`;
}
