import { Manifest, FunctionDef } from "./manifest.js";
import { generateTypeDefinitions } from "./types.js";

function toPascalCase(str: string) {
    return str.replace(/(^|_)([a-z])/g, (g) => g.at(-1)!.toUpperCase());
}

export function generateClientSDK(manifest: Manifest, includeTypes: boolean = false): string {
  // Separate regular functions from subscriptions
  const regularFunctions = Object.entries(manifest.functions)
    .filter(([_, def]) => !def.isSubscription);
  const subscriptionFunctions = Object.entries(manifest.functions)
    .filter(([_, def]) => def.isSubscription);

  // --- JavaScript SDK ---
  const jsCode = `
// Generated by TZQL Compiler v${manifest.version}
// Do not edit this file directly.

import { WebSocketManager } from 'tzql/client';

class GeneratedWebSocketManager extends WebSocketManager {
  constructor(options = {}) {
    super(options);
    this.api = {
${regularFunctions.map(([funcName]) =>
      `      ${funcName}: (params) => this.call('${funcName}', params),`
).join('\n')}
${subscriptionFunctions.map(([funcName]) =>
      `      ${funcName}: (params, callback) => this.subscribe('${funcName}', params, callback),`
).join('\n')}
    };
  }
}

export const ws = new GeneratedWebSocketManager();
`;

  // --- TypeScript Definitions ---
  if (includeTypes) {
    const typeDefs = generateTypeDefinitions(manifest.entities, manifest.subscribables);

    const tsCode = `
// Generated by TZQL Compiler v${manifest.version}
// Do not edit this file directly.

import { WebSocketManager } from 'tzql/client';

${typeDefs}

export interface TzqlAPI {
${Object.entries(manifest.functions).map(([funcName, def]) => {
    const isSubscription = def.isSubscription;
    const parts = funcName.split('_');
    const op = parts[0];
    const entity = parts.slice(1).join('_');
    const pascalEntity = toPascalCase(entity);

    // Check if this entity exists in manifest
    const entityExists = manifest.entities[entity];

    let paramType = 'Record<string, unknown>';
    let returnType = 'unknown';

    if (isSubscription) {
        // subscribe_venue_detail -> VenueDetailParams
        paramType = `${pascalEntity}Params`;
        returnType = 'void';
        return `  ${funcName}: (params: ${paramType}, callback: (data: unknown) => void) => Promise<${returnType}>;`;
    } else if (op === 'get' && entityExists) {
        // get_venue_detail (subscribable getter) vs get_venues (entity getter)
        if (manifest.subscribables?.[entity]) {
            paramType = `${pascalEntity}Params`;
            returnType = 'unknown'; // Could be typed based on subscribable structure
        } else {
            paramType = `${pascalEntity}PK`;
            returnType = `${pascalEntity} | null`;
        }
    } else if (op === 'save' && entityExists) {
        paramType = `Save${pascalEntity}Params`;
        returnType = pascalEntity;
    } else if (op === 'delete' && entityExists) {
        paramType = `${pascalEntity}PK`;
        returnType = pascalEntity;
    } else if (op === 'search' && entityExists) {
        paramType = `Search${pascalEntity}Params`;
        returnType = `${pascalEntity}[]`;
    } else if (op === 'lookup' && entityExists) {
        paramType = `Lookup${pascalEntity}Params`;
        returnType = `${pascalEntity}[]`;
    }
    // Custom functions and auth functions stay as Record<string, unknown>

    return `  ${funcName}: (params: ${paramType}) => Promise<${returnType}>;`;
}).join('\n')}
}

export class GeneratedWebSocketManager extends WebSocketManager {
  api: TzqlAPI;
}

export declare const ws: GeneratedWebSocketManager;
`;
    return tsCode;
  }

  return jsCode;
}
