import { Manifest } from "./manifest.js";

function toPascalCase(str: string): string {
  return str.replace(/(^|_)([a-z])/g, (g) => g[g.length - 1].toUpperCase());
}

export function generatePiniaStore(manifest: Manifest, entityName: string): string {
  const entity = manifest.entities[entityName];
  if (!entity) {
    throw new Error(`Entity '${entityName}' not found in manifest.`);
  }

  const pkField = entity.primaryKey[0] || 'id';
  const pascalName = toPascalCase(entityName);

  // Generate column types for TypeScript interface
  const columnTypes = entity.columns.map(col => {
    let tsType = 'unknown';
    const pgType = col.type.toLowerCase();

    if (pgType.includes('serial') || pgType.includes('int')) {
      tsType = 'number';
    } else if (pgType.includes('text') || pgType.includes('varchar') || pgType.includes('char')) {
      tsType = 'string';
    } else if (pgType.includes('bool')) {
      tsType = 'boolean';
    } else if (pgType.includes('timestamp') || pgType.includes('date')) {
      tsType = 'string'; // ISO date string
    } else if (pgType.includes('json')) {
      tsType = 'Record<string, unknown>';
    } else if (pgType.includes('decimal') || pgType.includes('numeric') || pgType.includes('float') || pgType.includes('real')) {
      tsType = 'number';
    }

    // Handle arrays
    if (col.isArray) {
      tsType = `${tsType}[]`;
    }

    // Make optional if not primary key and not NOT NULL
    const isRequired = pgType.includes('not null') || pgType.includes('primary key');
    return `  ${col.name}${isRequired ? '' : '?'}: ${tsType};`;
  }).join('\n');

  // Primary key type
  const pkCol = entity.columns.find(c => c.name === pkField);
  const pkType = pkCol && (pkCol.type.toLowerCase().includes('serial') || pkCol.type.toLowerCase().includes('int'))
    ? 'number'
    : 'string';

  return `// Generated by TZQL Compiler v${manifest.version}
// Do not edit this file directly.

import { defineStore } from 'pinia';
import { ref, type Ref } from 'vue';
import { ws } from '../../client.js';

/** ${pascalName} entity type */
export interface ${pascalName} {
${columnTypes}
}

/** Event payload for table changes */
export interface TableChangedPayload {
  table: string;
  operation: 'insert' | 'update' | 'delete';
  pk: { ${pkField}: ${pkType} };
  data: ${pascalName} | null;
}

export const use${pascalName}Store = defineStore('${entityName}-store', () => {
  const records: Ref<${pascalName}[]> = ref([]);
  const loading: Ref<boolean> = ref(false);
  const error: Ref<Error | null> = ref(null);

  async function get(id: ${pkType}): Promise<${pascalName} | null> {
    loading.value = true;
    try {
      const result = await ws.api.get_${entityName}({ ${pkField}: id });
      return result as ${pascalName} | null;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  }

  async function save(data: Partial<${pascalName}>): Promise<${pascalName}> {
    loading.value = true;
    try {
      const result = await ws.api.save_${entityName}(data);
      return result as ${pascalName};
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  }

  async function remove(id: ${pkType}): Promise<${pascalName}> {
    loading.value = true;
    try {
      const result = await ws.api.delete_${entityName}({ ${pkField}: id });
      return result as ${pascalName};
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  }

  async function search(query: {
    filters?: Record<string, unknown>;
    sort_field?: string;
    sort_order?: 'asc' | 'desc';
    limit?: number;
    offset?: number;
  } = {}): Promise<${pascalName}[]> {
    loading.value = true;
    try {
      const result = await ws.api.search_${entityName}(query);
      records.value = result as ${pascalName}[];
      return records.value;
    } catch (e) {
      error.value = e as Error;
      throw e;
    } finally {
      loading.value = false;
    }
  }

  function table_changed(payload: TableChangedPayload): void {
    if (payload.table === '${entityName}') {
      const pkValue = payload.pk?.${pkField};
      const existingIndex = records.value.findIndex((r: ${pascalName}) => r.${pkField} === pkValue);

      switch (payload.operation) {
        case 'insert':
          if (payload.data && existingIndex === -1) {
            records.value.push(payload.data);
          }
          break;
        case 'update':
          if (payload.data && existingIndex !== -1) {
            Object.assign(records.value[existingIndex], payload.data);
          } else if (payload.data) {
            records.value.push(payload.data);
          }
          break;
        case 'delete':
          if (existingIndex !== -1) {
            records.value.splice(existingIndex, 1);
          }
          break;
      }
    }
  }

  return {
    records,
    loading,
    error,
    get,
    save,
    remove,
    search,
    table_changed,
  };
});
`;
}
