import { Manifest } from "./manifest.js";

export function generatePiniaStore(manifest: Manifest, entityName: string): string {
  const entity = manifest.entities[entityName];
  if (!entity) {
    throw new Error(`Entity '${entityName}' not found in manifest.`);
  }

  const pkField = entity.primaryKey[0] || 'id'; // Assume single PK for simplicity

  return `
// Generated by TZQL Compiler v${manifest.version}
// Do not edit this file directly.

import { defineStore } from 'pinia';
import { ref } from 'vue';
import { ws } from '../../client.js'; // Adjust path as needed

export const use${entityName.charAt(0).toUpperCase() + entityName.slice(1)}Store = defineStore('${entityName}-store', () => {
  const records = ref([]);
  const loading = ref(false);
  const error = ref(null);

  async function get(id) {
    loading.value = true;
    try {
      const result = await ws.api.get_${entityName}({ ${pkField}: id });
      return result;
    } catch (e) {
      error.value = e;
      throw e;
    } finally {
      loading.value = false;
    }
  }

  async function save(data) {
    loading.value = true;
    try {
      const result = await ws.api.save_${entityName}(data);
      // For non-optimistic UI, we rely on the table_changed event
      return result;
    } catch (e) {
      error.value = e;
      throw e;
    } finally {
      loading.value = false;
    }
  }

  async function remove(id) {
    loading.value = true;
    try {
      const result = await ws.api.delete_${entityName}({ ${pkField}: id });
      // For non-optimistic UI, we rely on the table_changed event
      return result;
    } catch (e) {
      error.value = e;
      throw e;
    } finally {
      loading.value = false;
    }
  }

  // Global broadcast dispatcher handler
  // Updates local state based on atomic events
  async function table_changed(payload) {
    if (payload.table === '${entityName}') {
      const pkValue = payload.pk?.${pkField};
      const existingIndex = records.value.findIndex(r => r.${pkField} === pkValue);

      switch (payload.operation) {
        case 'insert':
          if (payload.data && existingIndex === -1) {
            records.value.push(payload.data);
          }
          break;
        case 'update':
          if (payload.data && existingIndex !== -1) {
            Object.assign(records.value[existingIndex], payload.data);
          } else if (payload.data) {
            // If item is not found, it might be a new item that passed filters, add it
            records.value.push(payload.data);
          }
          break;
        case 'delete':
          if (existingIndex !== -1) {
            records.value.splice(existingIndex, 1);
          }
          break;
      }
    }
  }

  return {
    records,
    loading,
    error,
    get,
    save,
    remove,
    table_changed,
  };
});
`;
}
