import { Manifest } from "./manifest.js";

function toPascalCase(str: string): string {
  return str.replace(/(^|_)([a-z])/g, (g) => g[g.length - 1].toUpperCase());
}

export function generateSubscribableStore(manifest: Manifest, subName: string): string {
  const sub = manifest.subscribables[subName];
  if (!sub) {
    throw new Error(`Subscribable '${subName}' not found in manifest.`);
  }

  const pascalName = toPascalCase(subName);
  const scopeTables = sub.scopeTables || [];
  const rootEntity = sub.root?.entity || '';

  // Generate params interface
  const paramEntries = Object.entries(sub.params);
  const paramsInterface = paramEntries.length > 0
    ? paramEntries.map(([name, pgType]) => {
        let tsType = 'unknown';
        const type = pgType.toLowerCase();
        if (type.includes('int')) tsType = 'number';
        else if (type.includes('text') || type.includes('varchar')) tsType = 'string';
        else if (type.includes('bool')) tsType = 'boolean';
        return `  ${name}: ${tsType};`;
      }).join('\n')
    : '  [key: string]: unknown;';

  // Generate path mappings for atomic updates
  const pathMappings = sub.includes ? generatePathMappings(rootEntity, sub.includes) : {};

  return `// Generated by DZQL Compiler v${manifest.version}
// Do not edit this file directly.

import { defineStore } from 'pinia';
import { ref, type Ref } from 'vue';
import { ws } from '../index.js';

/** Parameters for ${subName} subscription */
export interface ${pascalName}Params {
${paramsInterface}
}

/** Document wrapper with loading state */
export interface DocumentWrapper<T> {
  data: T;
  loading: boolean;
  ready: Promise<void>;
}

// Scope tables this subscribable cares about
const SCOPE_TABLES = ${JSON.stringify(scopeTables)};

// Path mappings: table -> path in document
const PATH_MAPPINGS: Record<string, string> = ${JSON.stringify(pathMappings)};

export const use${pascalName}Store = defineStore('sub-${subName}', () => {
  const documents: Ref<Record<string, DocumentWrapper<Record<string, unknown>>>> = ref({});

  async function bind(params: ${pascalName}Params): Promise<DocumentWrapper<Record<string, unknown>>> {
    const key = JSON.stringify(params);

    if (documents.value[key]) {
      const existing = documents.value[key];
      if (existing.loading) {
        await existing.ready;
      }
      return existing;
    }

    let resolveReady!: () => void;
    const ready = new Promise<void>((resolve) => { resolveReady = resolve; });

    documents.value[key] = { data: {}, loading: true, ready };

    // Subscribe to register interest and get initial data
    // Updates come via broadcasts to table_changed, not via callback
    const result = await ws.call('subscribe_${subName}', params) as { data: Record<string, unknown>; schema: unknown };
    Object.assign(documents.value[key].data, result.data);
    documents.value[key].loading = false;
    resolveReady();

    return documents.value[key];
  }

  function unbind(params: ${pascalName}Params): void {
    const key = JSON.stringify(params);
    // Unsubscribe to release server-side subscription
    ws.call('unsubscribe_${subName}', params).catch(() => {});
    delete documents.value[key];
  }

  // Broadcast handler - called by global dispatcher
  function table_changed(table: string, op: string, pk: Record<string, unknown>, data: unknown): void {
    if (!SCOPE_TABLES.includes(table)) return;

    const path = PATH_MAPPINGS[table];

    // Update all bound documents that might be affected
    for (const [key, doc] of Object.entries(documents.value)) {
      if (doc.loading) continue;
      applyUpdate(doc.data, table, path, op, pk, data);
    }
  }

  function applyUpdate(
    doc: Record<string, unknown>,
    table: string,
    path: string | undefined,
    op: string,
    pk: Record<string, unknown>,
    data: unknown
  ): void {
    if (!path) return;

    // Navigate to target
    const parts = path.split('.');
    let target: any = doc;
    for (let i = 0; i < parts.length - 1; i++) {
      target = target?.[parts[i]];
      if (!target) return;
    }

    const key = parts[parts.length - 1];
    const value = target[key];

    // If target is an object (single entity), update it directly
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      if (op === 'update' && data) {
        Object.assign(value, data as Record<string, unknown>);
      }
      return;
    }

    // If target is an array, handle insert/update/delete
    if (Array.isArray(value)) {
      const pkField = Object.keys(pk)[0] || 'id';
      const pkValue = pk[pkField];
      const idx = value.findIndex((item: any) => item?.[pkField] === pkValue);

      switch (op) {
        case 'insert':
          if (idx === -1 && data) value.push(data);
          break;
        case 'update':
          if (idx !== -1 && data) Object.assign(value[idx], data);
          break;
        case 'delete':
          if (idx !== -1) value.splice(idx, 1);
          break;
      }
    }
  }

  // Self-register with WebSocket for broadcasts
  ws.registerStore(table_changed);

  return { bind, unbind, documents, table_changed };
});
`;
}

function generatePathMappings(rootEntity: string, includes: Record<string, any>): Record<string, string> {
  const mappings: Record<string, string> = {};
  // Root entity is at its own key in the document (e.g., { venues: {...} })
  mappings[rootEntity] = rootEntity;

  function traverse(inc: Record<string, any>, prefix: string) {
    for (const [key, value] of Object.entries(inc)) {
      const entity = typeof value === 'string' ? value : value.entity || key;
      const path = prefix ? `${prefix}.${key}` : key;
      mappings[entity] = path;

      if (typeof value === 'object' && value.includes) {
        traverse(value.includes, path);
      }
    }
  }

  traverse(includes, '');
  return mappings;
}
