import { Manifest } from "./manifest.js";
import { SubscribableIR, IncludeIR } from "../../shared/ir.js";

function toPascalCase(str: string): string {
  return str.replace(/(^|_)([a-z])/g, (g) => g[g.length - 1].toUpperCase());
}

export function generateSubscribableStore(manifest: Manifest, subName: string): string {
  const sub = manifest.subscribables[subName];
  if (!sub) {
    throw new Error(`Subscribable '${subName}' not found in manifest.`);
  }

  const pascalName = toPascalCase(subName);

  // Generate params interface
  const paramEntries = Object.entries(sub.params);
  const paramsInterface = paramEntries.length > 0
    ? paramEntries.map(([name, pgType]) => {
        let tsType = 'unknown';
        const type = pgType.toLowerCase();
        if (type.includes('int')) tsType = 'number';
        else if (type.includes('text') || type.includes('varchar')) tsType = 'string';
        else if (type.includes('bool')) tsType = 'boolean';
        return `  ${name}: ${tsType};`;
      }).join('\n')
    : '  [key: string]: unknown;';

  // Helper to generate patch cases recursively
  const generatePatchCases = (): string => {
    const cases: string[] = [];

    // 1. Root Entity
    cases.push(
      `      case '${sub.root.entity}':\n` +
      `        if (event.op === 'update' && doc.${sub.root.entity}) {\n` +
      `          Object.assign(doc.${sub.root.entity}, event.data);\n` +
      `        }\n` +
      `        break;`
    );

    // 2. Recursive Includes
    const traverse = (includes: Record<string, IncludeIR>, pathStack: string[]) => {
      for (const [key, include] of Object.entries(includes)) {
        const entityName = include.entity;

        if (pathStack.length === 0) {
          // Level 1
          cases.push(
            `      case '${entityName}':\n` +
            `        handleArrayPatch(doc.${key}, event);\n` +
            `        break;`
          );
        } else {
          // Level 2+
          const level1Rel = pathStack[0];
          const singularParent = level1Rel.endsWith('s') ? level1Rel.slice(0, -1) : level1Rel;
          const fkField = `${singularParent}_id`;

          cases.push(
            `      case '${entityName}':\n` +
            `        if (event.data && (event.data as any).${fkField}) {\n` +
            `          const parent = (doc.${level1Rel} as any[])?.find((p: any) => p.id === (event.data as any).${fkField});\n` +
            `          if (parent && parent.${key}) {\n` +
            `            handleArrayPatch(parent.${key}, event);\n` +
            `          }\n` +
            `        }\n` +
            `        break;`
          );
        }

        if (include.includes) {
          traverse(include.includes, [...pathStack, key]);
        }
      }
    };

    traverse(sub.includes, []);
    return cases.join('\n');
  };

  const patchCases = generatePatchCases();

  return `// Generated by DZQL Compiler v${manifest.version}
// Do not edit this file directly.

import { defineStore } from 'pinia';
import { ref, type Ref } from 'vue';
import { ws } from '../index.js';

/** Parameters for ${subName} subscription */
export interface ${pascalName}Params {
${paramsInterface}
}

/** Event from server for patching */
export interface PatchEvent {
  table: string;
  op: 'insert' | 'update' | 'delete';
  pk: { id: number };
  data: Record<string, unknown> | null;
}

/** Document wrapper with loading state */
export interface DocumentWrapper<T> {
  data: T;
  loading: boolean;
  ready: Promise<void>;
}

export const use${pascalName}Store = defineStore('sub-${subName}', () => {
  const documents: Ref<Record<string, DocumentWrapper<Record<string, unknown>>>> = ref({});
  const unsubscribers = new Map<string, () => void>();

  async function bind(params: ${pascalName}Params): Promise<DocumentWrapper<Record<string, unknown>>> {
    const key = JSON.stringify(params);

    if (documents.value[key]) {
      const existing = documents.value[key];
      if (existing.loading) {
        await existing.ready;
      }
      return existing;
    }

    let resolveReady!: () => void;
    const ready = new Promise<void>((resolve) => { resolveReady = resolve; });

    documents.value[key] = { data: {}, loading: true, ready };
    let isFirst = true;

    const unsubscribe = await ws.api.subscribe_${subName}(params, (eventData: unknown) => {
      if (isFirst) {
        // Initial data - merge into existing object to preserve reactivity
        Object.assign(documents.value[key].data, eventData as Record<string, unknown>);
        documents.value[key].loading = false;
        isFirst = false;
        resolveReady();
      } else {
        // Patch event
        applyPatch(documents.value[key].data, eventData as PatchEvent);
      }
    });

    unsubscribers.set(key, unsubscribe as () => void);
    await ready;
    return documents.value[key];
  }

  function unbind(params: ${pascalName}Params): void {
    const key = JSON.stringify(params);
    const unsubscribe = unsubscribers.get(key);
    if (unsubscribe) {
      unsubscribe();
      unsubscribers.delete(key);
      delete documents.value[key];
    }
  }

  function applyPatch(doc: Record<string, unknown>, event: PatchEvent): void {
    if (!doc) return;
    switch (event.table) {
${patchCases}
    }
  }

  function handleArrayPatch(arr: any, event: PatchEvent): void {
    if (!arr || !Array.isArray(arr)) return;
    const pkValue = event.pk?.id;
    const idx = arr.findIndex((i: any) => i?.id === pkValue);

    if (event.op === 'insert') {
      if (idx === -1 && event.data) arr.push(event.data);
    } else if (event.op === 'update') {
      if (idx !== -1 && event.data) Object.assign(arr[idx], event.data);
    } else if (event.op === 'delete') {
      if (idx !== -1) arr.splice(idx, 1);
    }
  }

  return { bind, unbind, documents };
});
`;
}
