import { Manifest } from "./manifest.js";
import { SubscribableIR, IncludeIR } from "../../shared/ir.js";

function toPascalCase(str: string) {
    return str.replace(/(^|_)([a-z])/g, (g) => g[g.length-1].toUpperCase());
}

export function generateSubscribableStore(manifest: Manifest, subName: string): string {
  const sub = manifest.subscribables[subName];
  if (!sub) {
    throw new Error("Subscribable " + subName + " not found in manifest.");
  }

  // Helper to generate patch cases recursively
  const generatePatchCases = (): string => {
    const cases: string[] = [];

    // 1. Root Entity - target doc.{entity} since document structure is { entity: {...}, ... }
    cases.push(
      "      case '" + sub.root.entity + "':\n" +
      "        if (event.op === 'update' && doc." + sub.root.entity + ") Object.assign(doc." + sub.root.entity + ", event.data);\n" +
      "        break;"
    );

    // 2. Recursive Includes
    const traverse = (includes: Record<string, IncludeIR>, pathStack: string[]) => {
      for (const [key, include] of Object.entries(includes)) {
        const entityName = include.entity;

        if (pathStack.length === 0) {
             // Level 1
             cases.push(
      "      case '" + entityName + "':\n" +
      "        handleArrayPatch(doc." + key + ", event);\n" +
      "        break;"
             );
        } else {
            // Level 2+
            const level1Rel = pathStack[0];
            const singularParent = level1Rel.endsWith('s') ? level1Rel.slice(0, -1) : level1Rel;
            const fkField = singularParent + "_id";

            cases.push(
      "      case '" + entityName + "':\n" +
      "        if (event.data && event.data." + fkField + ") {\n" +
      "            const parent = doc." + level1Rel + ".find(p => p.id === event.data." + fkField + ");\n" +
      "            if (parent && parent." + key + ") {\n" +
      "                handleArrayPatch(parent." + key + ", event);\n" +
      "            }\n" +
      "        }\n" +
      "        break;"
            );
        }

        if (include.includes) {
            traverse(include.includes, [...pathStack, key]);
        }
      }
    };

    traverse(sub.includes, []);
    return cases.join('\n');
  };

  const patchCases = generatePatchCases();
  const pascalName = toPascalCase(subName);

  let output = "// Generated by TZQL Compiler v" + manifest.version + "\n";
  output += "// Do not edit this file directly.\n\n";
  output += "import { defineStore } from 'pinia';\n";
  output += "import { ref } from 'vue';\n";
  output += "import { ws } from '../index.js';\n\n";

  output += "export const use" + pascalName + "Store = defineStore('sub-" + subName + "', () => {\n";
  output += "  const documents = ref({});\n";
  output += "  const unsubscribers = new Map();\n\n";

  output += "  async function bind(params) {\n";
  output += "    const key = JSON.stringify(params);\n";
  output += "    if (documents.value[key]) {\n";
  output += "      const existing = documents.value[key];\n";
  output += "      if (existing.loading) {\n";
  output += "        await existing.ready;\n";
  output += "      }\n";
  output += "      return existing;\n";
  output += "    }\n\n";
  output += "    let resolveReady;\n";
  output += "    const ready = new Promise((resolve) => { resolveReady = resolve; });\n\n";
  output += "    documents.value[key] = { data: {}, loading: true, ready };\n";
  output += "    let isFirst = true;\n\n";
  output += "    const unsubscribe = await ws.api.subscribe_" + subName + "(params, (eventData) => {\n";
  output += "      if (isFirst) {\n";
  output += "        // Initial data - merge into existing object to preserve reactivity\n";
  output += "        Object.assign(documents.value[key].data, eventData);\n";
  output += "        documents.value[key].loading = false;\n";
  output += "        isFirst = false;\n";
  output += "        resolveReady();\n";
  output += "      } else {\n";
  output += "        // Patch event\n";
  output += "        applyPatch(documents.value[key].data, eventData);\n";
  output += "      }\n";
  output += "    });\n\n";
  output += "    unsubscribers.set(key, unsubscribe);\n";
  output += "    await ready;\n";
  output += "    return documents.value[key];\n";
  output += "  }\n\n";

  output += "  function unbind(params) {\n";
  output += "    const key = JSON.stringify(params);\n";
  output += "    const unsubscribe = unsubscribers.get(key);\n";
  output += "    if (unsubscribe) {\n";
  output += "      unsubscribe();\n";
  output += "      unsubscribers.delete(key);\n";
  output += "      delete documents.value[key];\n";
  output += "    }\n";
  output += "  }\n\n";

  output += "  function applyPatch(doc, event) {\n";
  output += "    if (!doc) return;\n";
  output += "    switch (event.table) {\n";
  output += patchCases + "\n";
  output += "    }\n";
  output += "  }\n\n";

  output += "  function handleArrayPatch(arr, event) {\n";
  output += "    if (!arr) return;\n";
  output += "    const pkValue = event.pk?.id;\n";
  output += "    const idx = arr.findIndex(i => i.id === pkValue);\n";
  output += "    if (event.op === 'insert') {\n";
  output += "       if (idx === -1) arr.push(event.data);\n";
  output += "    } else if (event.op === 'update') {\n";
  output += "       if (idx !== -1) Object.assign(arr[idx], event.data);\n";
  output += "    } else if (event.op === 'delete') {\n";
  output += "       if (idx !== -1) arr.splice(idx, 1);\n";
  output += "    }\n";
  output += "  }\n\n";

  output += "  return { bind, unbind, documents };\n";
  output += "});\n";

  return output;
}
