-- ============================================================================
-- DZQL Compiled Functions for: contractor_rights
-- Generated: 2025-11-16T08:35:10.417Z
--
-- This file was automatically generated by the DZQL Compiler.
-- Do not edit directly - regenerate from entity definition.
-- ============================================================================

-- Permission check: create on contractor_rights
CREATE OR REPLACE FUNCTION can_create_contractor_rights(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    EXISTS (
        SELECT 1 FROM acts_for
        WHERE acts_for.org_id = (p_record->>'sponsor_org_id')::int
          AND acts_for.valid_to IS NULL
          AND acts_for.user_id = p_user_id
      )
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: update on contractor_rights
CREATE OR REPLACE FUNCTION can_update_contractor_rights(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    EXISTS (
        SELECT 1 FROM acts_for
        WHERE acts_for.org_id = (p_record->>'sponsor_org_id')::int
          AND acts_for.valid_to IS NULL
          AND acts_for.user_id = p_user_id
      )
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: delete on contractor_rights
CREATE OR REPLACE FUNCTION can_delete_contractor_rights(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    EXISTS (
        SELECT 1 FROM acts_for
        WHERE acts_for.org_id = (p_record->>'sponsor_org_id')::int
          AND acts_for.valid_to IS NULL
          AND acts_for.user_id = p_user_id
      )
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: view on contractor_rights (public access)
CREATE OR REPLACE FUNCTION can_view_contractor_rights(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN true;  -- Public access
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- GET operation for contractor_rights
CREATE OR REPLACE FUNCTION get_contractor_rights(
  p_id INT,
  p_user_id INT,
  p_on_date TIMESTAMPTZ DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
  v_record contractor_rights%ROWTYPE;
BEGIN
  -- Fetch the record
  SELECT * INTO v_record
  FROM contractor_rights
  WHERE id = p_id
    AND valid_from <= COALESCE(p_on_date, NOW())
    AND (valid_to > COALESCE(p_on_date, NOW()) OR valid_to IS NULL);

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Record not found: % with id=%', 'contractor_rights', p_id;
  END IF;

  -- Convert to JSONB
  v_result := to_jsonb(v_record);

  -- Check view permission
  IF NOT can_view_contractor_rights(p_user_id, v_result) THEN
    RAISE EXCEPTION 'Permission denied: view on contractor_rights';
  END IF;


  -- Expand contractor_org (foreign key)
  IF v_record.contractor_org_id IS NOT NULL THEN
    v_result := v_result || jsonb_build_object(
      'contractor_org',
      (SELECT to_jsonb(t.*) FROM organisations t WHERE t.id = v_record.contractor_org_id)
    );
  END IF;
  -- Expand sponsor_org (foreign key)
  IF v_record.sponsor_org_id IS NOT NULL THEN
    v_result := v_result || jsonb_build_object(
      'sponsor_org',
      (SELECT to_jsonb(t.*) FROM organisations t WHERE t.id = v_record.sponsor_org_id)
    );
  END IF;
  -- Expand package (foreign key)
  IF v_record.package_id IS NOT NULL THEN
    v_result := v_result || jsonb_build_object(
      'package',
      (SELECT to_jsonb(t.*) FROM packages t WHERE t.id = v_record.package_id)
    );
  END IF;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SAVE operation for contractor_rights
CREATE OR REPLACE FUNCTION save_contractor_rights(
  p_data JSONB,
  p_user_id INT
) RETURNS JSONB AS $$
DECLARE
  v_result contractor_rights%ROWTYPE;
  v_existing contractor_rights%ROWTYPE;
  v_is_insert BOOLEAN := false;
  v_notify_users INT[];
BEGIN
  -- Determine if this is insert or update
  IF p_data->>'id' IS NULL THEN
    v_is_insert := true;
  ELSE
    -- Try to fetch existing record
    SELECT * INTO v_existing
    FROM contractor_rights
    WHERE id = (p_data->>'id')::int;

    v_is_insert := NOT FOUND;
  END IF;

  -- Check permissions
  IF v_is_insert THEN
    IF NOT can_create_contractor_rights(p_user_id, p_data) THEN
      RAISE EXCEPTION 'Permission denied: create on contractor_rights';
    END IF;
  ELSE
    IF NOT can_update_contractor_rights(p_user_id, to_jsonb(v_existing)) THEN
      RAISE EXCEPTION 'Permission denied: update on contractor_rights';
    END IF;
  END IF;

  -- Perform UPSERT
  IF v_is_insert THEN
    INSERT INTO contractor_rights (
      SELECT string_agg(quote_ident(key), ', ') FROM jsonb_object_keys(p_data) key
    ) VALUES (
      SELECT string_agg(quote_literal(value), ', ') FROM jsonb_each_text(p_data) kv(key, value)
    ) RETURNING * INTO v_result;
  ELSE
    UPDATE contractor_rights
    SET SELECT string_agg(quote_ident(key) || ' = ' || quote_literal(value), ', ')
      FROM jsonb_each_text(p_data) kv(key, value)
      WHERE key != 'id'
    WHERE id = (p_data->>'id')::int
    RETURNING * INTO v_result;
  END IF;



  -- Resolve notification recipients
  v_notify_users := resolve_notification_paths_contractor_rights(to_jsonb(v_result));

  RETURN to_jsonb(v_result);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- DELETE operation for contractor_rights
CREATE OR REPLACE FUNCTION delete_contractor_rights(
  p_id INT,
  p_user_id INT
) RETURNS JSONB AS $$
DECLARE
  v_result contractor_rights%ROWTYPE;
BEGIN
  -- Fetch record first
  SELECT * INTO v_result
  FROM contractor_rights
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Record not found: % with id=%', 'contractor_rights', p_id;
  END IF;

  -- Check delete permission
  IF NOT can_delete_contractor_rights(p_user_id, to_jsonb(v_result)) THEN
    RAISE EXCEPTION 'Permission denied: delete on contractor_rights';
  END IF;



  -- Perform delete
  DELETE FROM contractor_rights WHERE id = p_id RETURNING * INTO v_result;


  -- Resolve notification recipients
  v_notify_users := resolve_notification_paths_contractor_rights(to_jsonb(v_result));

  RETURN to_jsonb(v_result);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- LOOKUP operation for contractor_rights
CREATE OR REPLACE FUNCTION lookup_contractor_rights(
  p_filter TEXT DEFAULT NULL,
  p_user_id INT DEFAULT NULL,
  p_limit INT DEFAULT 50
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
BEGIN
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'value', id,
      'label', contractor_org_id
    ) ORDER BY contractor_org_id
  ), '[]'::jsonb) INTO v_result
  FROM contractor_rights
  WHERE (p_filter IS NULL OR contractor_org_id ILIKE '%' || p_filter || '%')
    AND valid_from <= COALESCE(p_on_date, NOW())
    AND (valid_to > COALESCE(p_on_date, NOW()) OR valid_to IS NULL)
  LIMIT p_limit;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SEARCH operation for contractor_rights
CREATE OR REPLACE FUNCTION search_contractor_rights(
  p_filters JSONB DEFAULT '{}',
  p_search TEXT DEFAULT NULL,
  p_sort JSONB DEFAULT NULL,
  p_page INT DEFAULT 1,
  p_limit INT DEFAULT 25,
  p_user_id INT DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_data JSONB;
  v_total INT;
  v_offset INT;
  v_sort_field TEXT;
  v_sort_order TEXT;
BEGIN
  v_offset := (p_page - 1) * p_limit;

  -- Extract sort parameters
  v_sort_field := COALESCE(p_sort->>'field', 'contractor_org_id');
  v_sort_order := COALESCE(p_sort->>'order', 'asc');

  -- Get total count
  SELECT COUNT(*) INTO v_total
  FROM contractor_rights
  WHERE (p_search IS NULL OR (contractor_org_id ILIKE '%' || p_search || '%' OR sponsor_org_id ILIKE '%' || p_search || '%'))
    AND valid_from <= COALESCE(p_on_date, NOW())
    AND (valid_to > COALESCE(p_on_date, NOW()) OR valid_to IS NULL);

  -- Get data
  EXECUTE format('
    SELECT COALESCE(jsonb_agg(to_jsonb(t.*) ORDER BY %I %s), ''[]''::jsonb)
    FROM contractor_rights t
    WHERE (CAST(%L AS TEXT) IS NULL OR (contractor_org_id ILIKE '%' || p_search || '%' OR sponsor_org_id ILIKE '%' || p_search || '%'))
    LIMIT %L OFFSET %L
  ', v_sort_field, v_sort_order, p_search, p_limit, v_offset) INTO v_data;

  RETURN jsonb_build_object(
    'data', v_data,
    'total', v_total,
    'page', p_page,
    'limit', p_limit
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Notification path resolution for contractor_rights
CREATE OR REPLACE FUNCTION resolve_notification_paths_contractor_rights(
  p_record JSONB
) RETURNS INT[] AS $$
DECLARE
  v_users INT[] := ARRAY[]::INT[];
BEGIN
  -- No notification paths configured

  -- Return unique user IDs
  RETURN ARRAY(SELECT DISTINCT unnest(v_users));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;