-- ============================================================================
-- DZQL Compiled Functions for: sites
-- Generated: 2025-11-16T08:35:10.417Z
--
-- This file was automatically generated by the DZQL Compiler.
-- Do not edit directly - regenerate from entity definition.
-- ============================================================================

-- Permission check: create on sites
CREATE OR REPLACE FUNCTION can_create_sites(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    EXISTS (
        SELECT 1 FROM acts_for
        WHERE acts_for.org_id = (p_record->>'null')::int
          AND acts_for.valid_to IS NULL
          AND acts_for.user_id = p_user_id
      )
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: update on sites
CREATE OR REPLACE FUNCTION can_update_sites(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    EXISTS (
        SELECT 1 FROM acts_for
        WHERE acts_for.org_id = (p_record->>'null')::int
          AND acts_for.valid_to IS NULL
          AND acts_for.user_id = p_user_id
      )
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: delete on sites
CREATE OR REPLACE FUNCTION can_delete_sites(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    EXISTS (
        SELECT 1 FROM acts_for
        WHERE acts_for.org_id = (p_record->>'null')::int
          AND acts_for.valid_to IS NULL
          AND acts_for.user_id = p_user_id
      )
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Permission check: view on sites (public access)
CREATE OR REPLACE FUNCTION can_view_sites(
  p_user_id INT,
  p_record JSONB
) RETURNS BOOLEAN AS $$
BEGIN
  RETURN true;  -- Public access
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- GET operation for sites
CREATE OR REPLACE FUNCTION get_sites(
  p_id INT,
  p_user_id INT,
  p_on_date TIMESTAMPTZ DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
  v_record sites%ROWTYPE;
BEGIN
  -- Fetch the record
  SELECT * INTO v_record
  FROM sites
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Record not found: % with id=%', 'sites', p_id;
  END IF;

  -- Convert to JSONB
  v_result := to_jsonb(v_record);

  -- Check view permission
  IF NOT can_view_sites(p_user_id, v_result) THEN
    RAISE EXCEPTION 'Permission denied: view on sites';
  END IF;


  -- Expand venue (foreign key)
  IF v_record.venue_id IS NOT NULL THEN
    v_result := v_result || jsonb_build_object(
      'venue',
      (SELECT to_jsonb(t.*) FROM venues t WHERE t.id = v_record.venue_id)
    );
  END IF;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SAVE operation for sites
CREATE OR REPLACE FUNCTION save_sites(
  p_data JSONB,
  p_user_id INT
) RETURNS JSONB AS $$
DECLARE
  v_result sites%ROWTYPE;
  v_existing sites%ROWTYPE;
  v_is_insert BOOLEAN := false;
  v_notify_users INT[];
BEGIN
  -- Determine if this is insert or update
  IF p_data->>'id' IS NULL THEN
    v_is_insert := true;
  ELSE
    -- Try to fetch existing record
    SELECT * INTO v_existing
    FROM sites
    WHERE id = (p_data->>'id')::int;

    v_is_insert := NOT FOUND;
  END IF;

  -- Check permissions
  IF v_is_insert THEN
    IF NOT can_create_sites(p_user_id, p_data) THEN
      RAISE EXCEPTION 'Permission denied: create on sites';
    END IF;
  ELSE
    IF NOT can_update_sites(p_user_id, to_jsonb(v_existing)) THEN
      RAISE EXCEPTION 'Permission denied: update on sites';
    END IF;
  END IF;

  -- Perform UPSERT
  IF v_is_insert THEN
    INSERT INTO sites (
      SELECT string_agg(quote_ident(key), ', ') FROM jsonb_object_keys(p_data) key
    ) VALUES (
      SELECT string_agg(quote_literal(value), ', ') FROM jsonb_each_text(p_data) kv(key, value)
    ) RETURNING * INTO v_result;
  ELSE
    UPDATE sites
    SET SELECT string_agg(quote_ident(key) || ' = ' || quote_literal(value), ', ')
      FROM jsonb_each_text(p_data) kv(key, value)
      WHERE key != 'id'
    WHERE id = (p_data->>'id')::int
    RETURNING * INTO v_result;
  END IF;



  -- Resolve notification recipients
  v_notify_users := resolve_notification_paths_sites(to_jsonb(v_result));

  RETURN to_jsonb(v_result);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- DELETE operation for sites
CREATE OR REPLACE FUNCTION delete_sites(
  p_id INT,
  p_user_id INT
) RETURNS JSONB AS $$
DECLARE
  v_result sites%ROWTYPE;
BEGIN
  -- Fetch record first
  SELECT * INTO v_result
  FROM sites
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Record not found: % with id=%', 'sites', p_id;
  END IF;

  -- Check delete permission
  IF NOT can_delete_sites(p_user_id, to_jsonb(v_result)) THEN
    RAISE EXCEPTION 'Permission denied: delete on sites';
  END IF;



  -- Perform delete
  DELETE FROM sites WHERE id = p_id RETURNING * INTO v_result;


  -- Resolve notification recipients
  v_notify_users := resolve_notification_paths_sites(to_jsonb(v_result));

  RETURN to_jsonb(v_result);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- LOOKUP operation for sites
CREATE OR REPLACE FUNCTION lookup_sites(
  p_filter TEXT DEFAULT NULL,
  p_user_id INT DEFAULT NULL,
  p_limit INT DEFAULT 50
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
BEGIN
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'value', id,
      'label', name
    ) ORDER BY name
  ), '[]'::jsonb) INTO v_result
  FROM sites
  WHERE (p_filter IS NULL OR name ILIKE '%' || p_filter || '%')
  LIMIT p_limit;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SEARCH operation for sites
CREATE OR REPLACE FUNCTION search_sites(
  p_filters JSONB DEFAULT '{}',
  p_search TEXT DEFAULT NULL,
  p_sort JSONB DEFAULT NULL,
  p_page INT DEFAULT 1,
  p_limit INT DEFAULT 25,
  p_user_id INT DEFAULT NULL
) RETURNS JSONB AS $$
DECLARE
  v_data JSONB;
  v_total INT;
  v_offset INT;
  v_sort_field TEXT;
  v_sort_order TEXT;
BEGIN
  v_offset := (p_page - 1) * p_limit;

  -- Extract sort parameters
  v_sort_field := COALESCE(p_sort->>'field', 'name');
  v_sort_order := COALESCE(p_sort->>'order', 'asc');

  -- Get total count
  SELECT COUNT(*) INTO v_total
  FROM sites
  WHERE (p_search IS NULL OR (name ILIKE '%' || p_search || '%' OR description ILIKE '%' || p_search || '%'));

  -- Get data
  EXECUTE format('
    SELECT COALESCE(jsonb_agg(to_jsonb(t.*) ORDER BY %I %s), ''[]''::jsonb)
    FROM sites t
    WHERE (CAST(%L AS TEXT) IS NULL OR (name ILIKE '%' || p_search || '%' OR description ILIKE '%' || p_search || '%'))
    LIMIT %L OFFSET %L
  ', v_sort_field, v_sort_order, p_search, p_limit, v_offset) INTO v_data;

  RETURN jsonb_build_object(
    'data', v_data,
    'total', v_total,
    'page', p_page,
    'limit', p_limit
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Notification path resolution for sites
CREATE OR REPLACE FUNCTION resolve_notification_paths_sites(
  p_record JSONB
) RETURNS INT[] AS $$
DECLARE
  v_users INT[] := ARRAY[]::INT[];
BEGIN
  -- No notification paths configured

  -- Return unique user IDs
  RETURN ARRAY(SELECT DISTINCT unnest(v_users));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;