-- ============================================================================
-- DZQL Core - Minimal Foundation (v3.0.0)
-- ============================================================================
-- This is the ONLY SQL you need to bootstrap DZQL.
-- Everything else is generated by: dzql compile entities.sql
-- ============================================================================

-- Required extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- DZQL schema
CREATE SCHEMA IF NOT EXISTS dzql;

-- Version tracking
CREATE TABLE IF NOT EXISTS dzql.meta (
  installed_at timestamptz DEFAULT now(),
  version text NOT NULL
);
INSERT INTO dzql.meta (version) VALUES ('3.0.0') ON CONFLICT DO NOTHING;

-- Entity registry (stores entity metadata for compiled functions)
CREATE TABLE IF NOT EXISTS dzql.entities (
  table_name text PRIMARY KEY,
  label_field text NOT NULL,
  searchable_fields text[] NOT NULL,
  fk_includes jsonb DEFAULT '{}',
  soft_delete boolean DEFAULT false,
  temporal_fields jsonb DEFAULT '{}',
  notification_paths jsonb DEFAULT '{}',
  permission_paths jsonb DEFAULT '{}',
  graph_rules jsonb DEFAULT '{}',
  field_defaults jsonb DEFAULT '{}',
  many_to_many jsonb DEFAULT '{}'
);

-- Function allowlist
CREATE TABLE IF NOT EXISTS dzql.registry (
  fn_regproc regproc PRIMARY KEY,
  description text
);

-- Event audit table (for real-time notifications via NOTIFY/LISTEN)
CREATE TABLE IF NOT EXISTS dzql.events (
  event_id bigserial PRIMARY KEY,
  table_name text NOT NULL,
  op text NOT NULL,
  pk jsonb NOT NULL,
  data jsonb,
  user_id int,
  notify_users int[],
  at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS dzql_events_at_idx ON dzql.events (at);
CREATE INDEX IF NOT EXISTS dzql_events_table_pk_idx ON dzql.events (table_name, pk, at);

-- NOTIFY trigger for real-time updates
CREATE OR REPLACE FUNCTION dzql.notify_event()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_notify('dzql', jsonb_build_object(
    'event_id', NEW.event_id,
    'table', NEW.table_name,
    'op', NEW.op,
    'pk', NEW.pk,
    'data', NEW.data,
    'user_id', NEW.user_id,
    'at', NEW.at,
    'notify_users', NEW.notify_users
  )::text);
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS dzql_events_notify ON dzql.events;
CREATE TRIGGER dzql_events_notify
  AFTER INSERT ON dzql.events
  FOR EACH ROW EXECUTE FUNCTION dzql.notify_event();

-- ============================================================================
-- That's it! Now run: dzql compile your-entities.sql -o compiled/
-- Then apply: psql $DATABASE_URL -f compiled/001_schema.sql -f compiled/users.sql ...
-- ============================================================================
